package com.learnkmp.myblog.model

data class Post(
    val id: String = "",
    val uuid: String = "",
    val title: String = "",
    val slug: String = "",
    val mobiledoc: String = "",
    val lexical: String = "",
    val html: String = "",
    val commentId: String = "",
    val plaintext: String = "",
    val featureImage: String = "",
    val featured: Int = 0,
    val type: String = "",
    val status: String = "",
    val locale: String = "",
    val visibility: String = "",
    val emailRecipientFilter: String = "",
    val createdAt: String = "",
    val updatedAt: String = "",
    val publishedAt: String = "",
    val customExcerpt: String = "",
    val codeinjectionHead: String = "",
    val codeinjectionFoot: String = "",
    val customTemplate: String = "",
    val canonicalUrl: String = "",
    val newsletterId: String = "",
    val showTitleAndFeatureImage: Int = 0
)

fun Post.toDTO() = PostDTO(
    id = id,
    uuid = uuid,
    title = title,
    slug = slug,
    mobiledoc = mobiledoc,
    lexical = lexical,
    html = html,
    commentId = commentId,
    plaintext = plaintext,
    featureImage = featureImage,
    featured = featured,
    type = type,
    status = status,
    locale = locale,
    visibility = visibility,
    emailRecipientFilter = emailRecipientFilter,
    createdAt = createdAt,
    updatedAt = updatedAt,
    publishedAt = publishedAt,
    customExcerpt = customExcerpt,
    codeinjectionHead = codeinjectionHead,
    codeinjectionFoot = codeinjectionFoot,
    customTemplate = customTemplate,
    canonicalUrl = canonicalUrl,
    newsletterId = newsletterId,
    showTitleAndFeatureImage = showTitleAndFeatureImage
)
